general:
steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
      org: 'c4e3bfcb-336c-42ad-ab50-8c87ebc09b94'
      space: 'dev'
      credentialsId: 'cfcredentials'
